# TAIF Project

## Sprint 2 - Evidence Collection

### Purpose

Collect financial evidence from external information sources.

---

### Input

- Stock ID

---

### Output

data/evidence/evidence_2330.csv

---

### Current Provider

- Google News RSS

---

### Future Providers

- Yahoo Finance
- TWSE
- MOPS
- Financial Reports

---

Author

SHENG HSU

Version

Sprint 2.4

In [50]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [51]:
import sys
from pathlib import Path

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [52]:
from pathlib import Path

# TAIF 專案根目錄
PROJECT_ROOT = Path("/content/drive/MyDrive/TAIF")

# 加入 Python 搜尋路徑
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

# Data Folder
RAW_DATA = PROJECT_ROOT / "data" / "raw"
PROCESSED_DATA = PROJECT_ROOT / "data" / "processed"
EVIDENCE_DATA = PROJECT_ROOT / "data" / "evidence"

print("Project Root :", PROJECT_ROOT)
print("Evidence Folder :", EVIDENCE_DATA)

Project Root : /content/drive/MyDrive/TAIF
Evidence Folder : /content/drive/MyDrive/TAIF/data/evidence

In [53]:
from src.evidence_collector import EvidenceCollector

print("EvidenceCollector imported successfully!")

EvidenceCollector imported successfully!

In [54]:
collector = EvidenceCollector()

print("Collector Ready!")

EvidenceCollector initialized.
Collector Ready!

In [55]:
results = collector.collect(
    stock_id="2330",
    company_name="台積電",
    limit=10
)

len(results)

10

In [56]:
df = pd.DataFrame(results)

df.head()

,evidence_id,stock_id,company,published_time,title,source,url,content,evidence_type
0,2330_0001,2330,台積電,"Thu, 30 Jul 2026 13:00:00 GMT",TSMC Develops AI Chip Packaging Tech to Counte...,"""台積電"" - Google News",https://news.google.com/rss/articles/CBMilAFBV...,"<a href=""https://news.google.com/rss/articles/...",news
1,2330_0002,2330,台積電,"Thu, 30 Jul 2026 19:53:43 GMT",TSMC's next AI chip move sends Intel stock soa...,"""台積電"" - Google News",https://news.google.com/rss/articles/CBMikAFBV...,"<a href=""https://news.google.com/rss/articles/...",news
2,2330_0003,2330,台積電,"Thu, 30 Jul 2026 16:08:28 GMT",TSMC Develops EMIB-like Technology to Compete ...,"""台積電"" - Google News",https://news.google.com/rss/articles/CBMilgFBV...,"<a href=""https://news.google.com/rss/articles/...",news
3,2330_0004,2330,台積電,"Thu, 30 Jul 2026 14:46:00 GMT",TSMC Stock Gains On Report Of Developing 'EMIB...,"""台積電"" - Google News",https://news.google.com/rss/articles/CBMiswFBV...,"<a href=""https://news.google.com/rss/articles/...",news
4,2330_0005,2330,台積電,"Tue, 28 Jul 2026 22:25:12 GMT",Intel Vs. TSMC: How CoWoS Packaging Constraint...,"""台積電"" - Google News",https://news.google.com/rss/articles/CBMiwAFBV...,"<a href=""https://news.google.com/rss/articles/...",news

In [57]:
print(f"Number of Evidence : {len(df)}")

print()

print(df.info())

Number of Evidence : 10

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   evidence_id     10 non-null     object
 1   stock_id        10 non-null     object
 2   company         10 non-null     object
 3   published_time  10 non-null     object
 4   title           10 non-null     object
 5   source          10 non-null     object
 6   url             10 non-null     object
 7   content         10 non-null     object
 8   evidence_type   10 non-null     object
dtypes: object(9)
memory usage: 852.0+ bytes
None

In [58]:
output_file = EVIDENCE_DATA / "evidence_2330.csv"

df.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:", output_file)

Saved: /content/drive/MyDrive/TAIF/data/evidence/evidence_2330.csv

In [59]:
df.head(10)

,evidence_id,stock_id,company,published_time,title,source,url,content,evidence_type
0,2330_0001,2330,台積電,"Thu, 30 Jul 2026 13:00:00 GMT",TSMC Develops AI Chip Packaging Tech to Counte...,"""台積電"" - Google News",https://news.google.com/rss/articles/CBMilAFBV...,"<a href=""https://news.google.com/rss/articles/...",news
1,2330_0002,2330,台積電,"Thu, 30 Jul 2026 19:53:43 GMT",TSMC's next AI chip move sends Intel stock soa...,"""台積電"" - Google News",https://news.google.com/rss/articles/CBMikAFBV...,"<a href=""https://news.google.com/rss/articles/...",news
2,2330_0003,2330,台積電,"Thu, 30 Jul 2026 16:08:28 GMT",TSMC Develops EMIB-like Technology to Compete ...,"""台積電"" - Google News",https://news.google.com/rss/articles/CBMilgFBV...,"<a href=""https://news.google.com/rss/articles/...",news
3,2330_0004,2330,台積電,"Thu, 30 Jul 2026 14:46:00 GMT",TSMC Stock Gains On Report Of Developing 'EMIB...,"""台積電"" - Google News",https://news.google.com/rss/articles/CBMiswFBV...,"<a href=""https://news.google.com/rss/articles/...",news
4,2330_0005,2330,台積電,"Tue, 28 Jul 2026 22:25:12 GMT",Intel Vs. TSMC: How CoWoS Packaging Constraint...,"""台積電"" - Google News",https://news.google.com/rss/articles/CBMiwAFBV...,"<a href=""https://news.google.com/rss/articles/...",news
5,2330_0006,2330,台積電,"Thu, 30 Jul 2026 13:22:32 GMT",Why Is Intel Stock (INTC) Jumping Over 14% Tod...,"""台積電"" - Google News",https://news.google.com/rss/articles/CBMiswFBV...,"<a href=""https://news.google.com/rss/articles/...",news
6,2330_0007,2330,台積電,"Tue, 28 Jul 2026 14:27:32 GMT",TSMC says Japan plant gradually resuming opera...,"""台積電"" - Google News",https://news.google.com/rss/articles/CBMiwAFBV...,"<a href=""https://news.google.com/rss/articles/...",news
7,2330_0008,2330,台積電,"Thu, 30 Jul 2026 10:05:28 GMT",TSMC’s AI Implementation Helps 1.4nm Progress ...,"""台積電"" - Google News",https://news.google.com/rss/articles/CBMijgFBV...,"<a href=""https://news.google.com/rss/articles/...",news
8,2330_0009,2330,台積電,"Thu, 30 Jul 2026 05:00:45 GMT",[News] TSMC’s 1.4nm Fab Ahead of Schedule; Fir...,"""台積電"" - Google News",https://news.google.com/rss/articles/CBMi6wFBV...,"<a href=""https://news.google.com/rss/articles/...",news
9,2330_0010,2330,台積電,"Tue, 28 Jul 2026 21:00:00 GMT",TSMC and Tencent break into the top 100 of the...,"""台積電"" - Google News",https://news.google.com/rss/articles/CBMinwFBV...,"<a href=""https://news.google.com/rss/articles/...",news

---

## Sprint 2 Completed

### Output

```
data/evidence/evidence_2330.csv
```

### Next

Sprint 3

LLM Reasoning